services:
  - type: worker
    name: telegram-auto-approval-bot
    env: python
    pythonVersion: "3.11"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot/main.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_USER_IDS
        sync: false
      - key: MONGO_URI
        sync: false
      - key: FORCE_SUB_CHANNEL
        sync: false
      - key: LOG_CHANNEL_ID
        sync: false
